export {default as Home} from "./home/Home"
export {default as Contact} from "./contact/Contact"
export {default as Login} from "./auth/Login"
export {default as Register} from "./auth/Register"
export {default as Reset} from "./auth/Reset"
export {default as Admin} from "./admin/Admin"
export {default as Cart} from "./cart/Cart"
export {default as ProductSlider} from './products/product/ProductSlider'
export {default as AllProduct} from './products/product/AllProduct'
